services:
  score-service:
    container_name: score-service
    image: score-service
    build: ./
    environment:
      - DB_PATH=/home/db/database.db
    volumes:
      - type: bind
        source: ./database.db
        target: /home/db/database.db
    ports:
      - "9000:9000"

